# Generated by Django 5.0.1 on 2024-02-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrecipe', '0002_remove_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(),
        ),
    ]
